"""meses_gracia_pago y telefono profesor

Revision ID: 0678db8d6d4f
Revises: 5415aa6cb86f
Create Date: 2026-09-29 02:50:01.049397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0678db8d6d4f'
down_revision: Union[str, None] = '5415aa6cb86f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'school_config',
        sa.Column('meses_gracia_pago', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column('usuarios', sa.Column('telefono', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'telefono')
    op.drop_column('school_config', 'meses_gracia_pago')
    # ### end Alembic commands ###
