"""alumnos

Revision ID: 0bd678d9d8e8
Revises: e00010035ee2
Create Date: 2026-07-19 00:04:23.275310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd678d9d8e8'
down_revision: Union[str, None] = 'e00010035ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_identificacion', sa.String(length=50), nullable=False),
    sa.Column('nombres', sa.String(length=150), nullable=False),
    sa.Column('apellidos', sa.String(length=150), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('foto_path', sa.String(length=255), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('categoria_override', sa.Boolean(), nullable=False),
    sa.Column('acudiente_nombre', sa.String(length=150), nullable=False),
    sa.Column('acudiente_telefono', sa.String(length=30), nullable=False),
    sa.Column('acudiente_email', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumnos_numero_identificacion'), 'alumnos', ['numero_identificacion'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alumnos_numero_identificacion'), table_name='alumnos')
    op.drop_table('alumnos')
    # ### end Alembic commands ###
