"""school_config_fecha_inicio

Revision ID: 304c44032620
Revises: 8d06a454cc00
Create Date: 2026-07-19 01:22:00.000996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '304c44032620'
down_revision: Union[str, None] = '8d06a454cc00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_config', sa.Column('fecha_inicio', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_config', 'fecha_inicio')
    # ### end Alembic commands ###
