"""profesor desacoplado de usuario

Revision ID: 4542a1f2e22b
Revises: 0678db8d6d4f
Create Date: 2026-10-01 00:48:33.405826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4542a1f2e22b'
down_revision: Union[str, None] = '0678db8d6d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profesores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profesor_categoria',
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profesor_id', 'categoria_id')
    )
    op.drop_column('usuarios', 'telefono')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('telefono', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_table('profesor_categoria')
    op.drop_table('profesores')
    # ### end Alembic commands ###
