"""pago_token_publico

Revision ID: 5415aa6cb86f
Revises: c1d0bf4e9014
Create Date: 2026-09-16 00:42:41.184587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5415aa6cb86f'
down_revision: Union[str, None] = 'c1d0bf4e9014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjustado a mano: server_default
    # con gen_random_uuid() (built-in desde Postgres 13) para que cada pago ya
    # existente reciba un token distinto, no un mismo valor fijo repetido (lo
    # cual violaría el unique constraint). Los pagos nuevos igual reciben su
    # propio UUID desde el modelo de SQLAlchemy al insertarse.
    op.add_column(
        'pagos',
        sa.Column('token', sa.String(length=36), nullable=False, server_default=sa.text('gen_random_uuid()::text')),
    )
    op.create_unique_constraint(None, 'pagos', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pagos', type_='unique')
    op.drop_column('pagos', 'token')
    # ### end Alembic commands ###
