"""notification_log

Revision ID: 8d06a454cc00
Revises: ad4e508266ab
Create Date: 2026-07-19 00:46:44.252738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d06a454cc00'
down_revision: Union[str, None] = 'ad4e508266ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('mensualidad_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('enviado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('exitoso', sa.Boolean(), nullable=False),
    sa.Column('detalle_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['mensualidad_id'], ['mensualidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mensualidad_id', 'tipo', 'canal', name='uq_mensualidad_tipo_canal')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_log')
    # ### end Alembic commands ###
