"""pagos

Revision ID: ad4e508266ab
Revises: fdede75f4a8f
Create Date: 2026-07-19 00:42:01.248456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad4e508266ab'
down_revision: Union[str, None] = 'fdede75f4a8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mensualidad_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('metodo_pago', sa.String(length=30), nullable=False),
    sa.Column('recibo_tipo', sa.String(length=20), nullable=False),
    sa.Column('recibo_path', sa.String(length=255), nullable=False),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mensualidad_id'], ['mensualidades.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos')
    # ### end Alembic commands ###
