"""recibo_oficial_pago

Revision ID: c1d0bf4e9014
Revises: 304c44032620
Create Date: 2026-09-16 00:26:24.786269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1d0bf4e9014'
down_revision: Union[str, None] = '304c44032620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjustado a mano: server_default
    # para que los pagos ya existentes (previos a esta migración, sin foto de
    # datos) no rompan el NOT NULL. Los pagos nuevos siempre reciben los valores
    # reales desde el router al crearse.
    op.add_column('pagos', sa.Column('referencia', sa.String(length=100), nullable=True))
    op.add_column('pagos', sa.Column('observaciones', sa.Text(), nullable=True))
    op.add_column('pagos', sa.Column('alumno_nombre', sa.String(length=300), nullable=False, server_default=''))
    op.add_column('pagos', sa.Column('categoria_nombre', sa.String(length=100), nullable=False, server_default=''))
    op.add_column('pagos', sa.Column('acudiente_nombre', sa.String(length=150), nullable=False, server_default=''))
    op.add_column('pagos', sa.Column('acudiente_telefono', sa.String(length=30), nullable=False, server_default=''))
    op.add_column('pagos', sa.Column('periodo_texto', sa.String(length=100), nullable=False, server_default=''))
    op.add_column(
        'pagos',
        sa.Column('conceptos', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagos', 'conceptos')
    op.drop_column('pagos', 'periodo_texto')
    op.drop_column('pagos', 'acudiente_telefono')
    op.drop_column('pagos', 'acudiente_nombre')
    op.drop_column('pagos', 'categoria_nombre')
    op.drop_column('pagos', 'alumno_nombre')
    op.drop_column('pagos', 'observaciones')
    op.drop_column('pagos', 'referencia')
    # ### end Alembic commands ###
