"""numero_identificacion para profesor

Revision ID: d6b2c995267e
Revises: 4542a1f2e22b
Create Date: 2026-10-02 02:43:45.065346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b2c995267e'
down_revision: Union[str, None] = '4542a1f2e22b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Columna UNIQUE+NOT NULL sobre una tabla que ya puede tener filas (ver gotcha de
    # migraciones en CLAUDE.md): un server_default fijo violaría la unicidad, así que
    # se agrega nullable, se backfillea con un placeholder distinto por fila (basado
    # en el id) y luego se endurece a NOT NULL. Quien ya tenía profesores cargados
    # deberá reemplazar el placeholder por la identificación real desde la UI.
    op.add_column('profesores', sa.Column('numero_identificacion', sa.String(length=50), nullable=True))
    op.execute("UPDATE profesores SET numero_identificacion = 'PENDIENTE-' || id WHERE numero_identificacion IS NULL")
    op.alter_column('profesores', 'numero_identificacion', nullable=False)
    op.create_index(op.f('ix_profesores_numero_identificacion'), 'profesores', ['numero_identificacion'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profesores_numero_identificacion'), table_name='profesores')
    op.drop_column('profesores', 'numero_identificacion')
    # ### end Alembic commands ###
