"""school_config_mensualidades

Revision ID: fdede75f4a8f
Revises: 0bd678d9d8e8
Create Date: 2026-07-19 00:33:18.871591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdede75f4a8f'
down_revision: Union[str, None] = '0bd678d9d8e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_escuela', sa.String(length=150), nullable=False),
    sa.Column('valor_mensualidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dia_corte', sa.Integer(), nullable=False),
    sa.Column('dias_recordatorio_previo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensualidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('periodo_inicio', sa.Date(), nullable=False),
    sa.Column('periodo_fin', sa.Date(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_prorrateado', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alumno_id', 'periodo_inicio', name='uq_alumno_periodo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensualidades')
    op.drop_table('school_config')
    # ### end Alembic commands ###
